development:
  adapter: postgresql
  encoding: unicode
  database: dummy_qc_admin_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dummy_qc_admin_test
  pool: 5
  username: postgres
  password:
