development:
  adapter: postgresql
  encoding: unicode
  database: dummy_development_no_later
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dummy_test_no_later
  pool: 5
  username: postgres
  password:
